---
- hosts: ansible_jump
  become: yes
  
  roles:

    - role: singleplatform-eng.users    
      tags: 
        - users
        - stage:build

    - role: ahuffman.sudoers
      tags: 
        - sudo
        - sudoers
        - stage:build

    - role: willshersystems.sshd
      tags: 
        - sshd
        - ssh
        - stage:build

    - role: geerlingguy.ntp
      tags: 
        - ntp
        - ntpd
        - stage:build

    - role: sbaerlocher.snmp
      tags: 
        - snmp
        - snmpd

    - role: geerlingguy.firewall
      tags: 
        - firewall
        - firewalld
        - iptables    
        - stage:build

